### ISSUE TITLE
compiletime getBuildMapData

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#878]
in `wurst.build`
```
---
projectName: "foo"
dependencies:
- "https://github.com/wurstscript/wurstStdlib2"
buildMapData:
  name: "foo"
  fileName: "foo"
  author: "foo"
  playerCount: 5
  someInt: 5//custom
  someTip:"hello world" //custom
```
new compiletime MagicFunctions `getBuildMapData*type*(string)->*type*`
```
int version = compiletime(getBuildMapDataInt("someInt"))
var tip = compiletime(getBuildMapDataString("someTip"))

init
    print(version)
    print(tip)
```
